# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CitiBank' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CitiBank
  pod 'M13Checkbox'
  pod 'TwicketSegmentedControl'
  pod ‘TextFieldEffects’
  target 'CitiBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CitiBankUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
